[FOR RE-REVIEW] fix greenrush issues
MediaJel/mediajel-tracker pull request #121
Opened 2022-06-06 14:45 UTC by jrleonardo

Description:
Fix greenrush issue on not getting transaction data for v1 and v2.

2022-06-06 16:29 UTC, pacholoamit approved these changes
Hello, looks good.

2022-06-06 16:35 UTC, vancebaritugo requested changes

2022-06-06 17:04 UTC, jrleonardo commented on src/v1/imports/carts/greenrush.ts
>                item.quantity,
applied error handling

2022-06-06 17:04 UTC, jrleonardo commented on src/v1/imports/carts/greenrush.ts
>                "US"
done changing to USD

2022-06-06 17:05 UTC, jrleonardo commented on src/v1/imports/carts/greenrush.ts
> +          return;
removed else statement

2022-06-07 08:53 UTC, vancebaritugo approved these changes

2022-06-07 08:53 UTC, merged