magento version one staging
MediaJel/mediajel-tracker pull request #345
Opened 2023-10-25 09:57 UTC by jonmediajel

2023-10-25 16:24 UTC, pacholoamit requested changes
Hello, please see feedback. Thanks!

2023-10-25 16:24 UTC, pacholoamit commented on src/shared/environment-data-sources/magento.ts
> +      const getData = JSON.parse(JSON.stringify(JSON.parse(xhr.responseText)));
why do we parse then stringify then parse again?

2023-10-25 16:24 UTC, pacholoamit commented on src/v2/imports/carts/magento.ts
> +        const checkoutSuccessElement = document.querySelector(".checkout-success");
This entire section is incorrect. Lets sync up regarding what the v2 is for

2023-10-30 08:52 UTC, jonmediajel commented
Thanks for the review @pacholoamit. Feedbacks are now fixed

2023-10-30 09:20 UTC, pacholoamit commented
> Thanks for the review @pacholoamit. Feedbacks are now fixed

Thanks

2023-10-31 16:43 UTC, pacholoamit commented on src/v2/imports/carts/magento.ts
you should be able to use the `magentoDataSource` here... Similar to what you did on `src/v1/imports/carts/magento.ts`

2023-11-01 04:45 UTC, jonmediajel commented
all goods now @pacholoamit , thanks

2023-11-01 12:23 UTC, pacholoamit approved these changes
Beautiful

2023-11-01 12:23 UTC, merged