feat: Add datalayersource to magento cart
MediaJel/mediajel-tracker pull request #542
Opened 2024-10-21 22:33 UTC by ZeeLiger

2024-10-21 22:41 UTC, SeanRizarre requested changes

2024-10-21 22:41 UTC, SeanRizarre commented on src/shared/environment-data-sources/magento.ts
> +          tax: parseFloat(ecommerce.tax),
Missing shipping here

2024-10-21 22:48 UTC, SeanRizarre commented on src/shared/environment-data-sources/magento.ts
> +
Add condition to trigger 2nd use case

2024-10-22 01:09 UTC, SeanRizarre commented
LGTM!!

2024-10-22 01:09 UTC, SeanRizarre approved these changes

2024-10-22 15:22 UTC, pacholoamit requested changes
Are we sure this works?

So at first we listen to the xhr response. Then we have a success boolean to evaluate when to listen to the datalayerSource but if you think about it, it's always going to be false.

When this code gets added to the page in the browser, xhrResponseSource runs then immediately after that it checks if success is true or false, which, it should be always false right? By the time success is equal to true the datalayserSource code has already been loaded to the DOM so having the success boolean doesn't really do anything.

2024-10-23 10:49 UTC, SeanRizarre commented
Made a script for the code and tested it out on the site, doesn't work. Will be making a revision now

2024-10-23 11:43 UTC, SeanRizarre commented
Perhaps we can use this
```javascript
<script>
    const isTrackerLoaded = (callback) => {
        if (window.tracker) {
            callback();
        } else {
            let trackerLoaded = false;
            const intervalId = setInterval(() => {
            if (window.tracker && !trackerLoaded) {
                trackerLoaded = true;
                clearInterval(intervalId);
                callback();
            }
            }, 100);
        }
    };

    window.dataLayer = window.dataLayer || [];
    for (let i = 0; i < window.dataLayer.length; i++) {
        const data = window.dataLayer[i];
        console.log(data);

        console.log("Inside dataLayerSource");
        console.log("Events: ", data.event);
        if (data.event === "purchase") {
            console.log("GOTCHA BITCH");
        }

        if(data.event === "purchase") {
            console.log("Inside purchase");
            const ecommerce = data.ecommerce;
            console.log("DATA:", ecommerce);

            isTrackerLoaded(() => {
                window.tracker("addTrans", {
                    orderId: ecommerce.transaction_id.toString(),
                    affiliation: "N/A",
                    total: parseFloat(ecommerce.value),
                    tax: parseFloat(ecommerce.tax) || 0,
                    shipping: parseFloat(ecommerce.shipping) || 0,
                    city: "N/A",
                    state: "N/A",
                    country: "N/A",
                    currency: "USD",
                });
                console.log("Tracker 1 loaded");

                ecommerce.items.forEach((item) => {
                    window.tracker("addItem", {
                        orderId: ecommerce.transaction_id.toString(),
                        sku: item.id.toString(),
                        name: (item.name || "N/A").toString(),
                        category: (item.category || "N/A").toString(),
                        price: parseFloat(item.price || 0),
                        quantity: parseInt(item.quantity || 1),
                        currency: "USD",
                    });
                });
                console.log("Tracker 2 loaded");

                window.tracker("trackTrans");
                console.log("DatalayerSource Tracked Transactions!");
            });
        }
    }
</script>
```

2024-10-23 12:33 UTC, SeanRizarre approved these changes
LGTM! Tested locally and working

2024-10-23 20:34 UTC, SeanRizarre commented
Minor improvements:
Make xhrResponseSource available before the if statement just after the datalayerSource transaction.

2024-10-25 18:43 UTC, pacholoamit approved these changes

2024-10-25 18:44 UTC, merged