fix: Google Ads plugin us to not track for display sometimes
MediaJel/mediajel-tracker pull request #548
Opened 2024-10-31 21:56 UTC by pacholoamit

2024-10-31 22:22 UTC, SeanRizarre commented
Working on my side even after the refresh! LGTM!
![image](https://github.com/user-attachments/assets/a4a440f9-ec75-44ae-b0ad-d786bd7df3ab)
![image](https://github.com/user-attachments/assets/665c536d-21c0-4080-a4aa-27172a9753a2)

2024-10-31 22:22 UTC, SeanRizarre approved these changes

2024-11-01 01:26 UTC, jonmediajel requested changes
Looks good, although I am not sure why is this having an error

![image](https://github.com/user-attachments/assets/534f2b33-6a34-405a-b2e1-f08e9390fe67)

Although conversions are running well on my end

![image](https://github.com/user-attachments/assets/79d40500-7c8a-4abc-ad0c-f6963a0f0b80)

2024-11-01 08:36 UTC, jonmediajel approved these changes
Greatwork! Verified google ads and display are working well

2024-11-04 15:17 UTC, merged